catalogs:
  mlb:
    MLB ETL:
      privileges:
        - USE CATALOG

schemas:
  mlb.bronze:
    MLB ETL:
      privileges:
        - USE SCHEMA
        - SELECT
        - CREATE TABLE
        - MODIFY

  mlb.silver:
    MLB ETL:
      privileges:
        - USE SCHEMA
        - SELECT
        - CREATE TABLE
        - MODIFY