service_accounts:

  cloud_run:

    id: mlb-cloud-run-sa

    display_name: MLB Cloud Run

    description: >
      Executes Cloud Run services that retrieve MLB Stats API data
      and write JSON files into Cloud Storage.

  databricks:

    id: mlb-databricks-sa

    display_name: MLB Databricks

    description: >
      Executes Databricks workloads that read landing files from
      Cloud Storage, process Bronze and Silver layers and publish
      Gold tables into BigQuery.

  power_bi:

    id: mlb-powerbi-sa

    display_name: MLB Power BI

    description: >
      Reads analytical tables from BigQuery.