table:
  name: game
  schema: bronze
  description: This table contains the raw JSON response from the MLB API for a specific game.

  columns:
    - name: game_pk
      type: INT
      description: MLB unique identifier for the game

    - name: season
      type: INT
      description: MLB season year

    - name: raw_response
      type: STRING
      description: Raw JSON response from the MLB API

    - name: ingestion_timestamp
      type: TIMESTAMP
      description: Timestamp of when the data was ingested

  partition:
    field: season