table:
  name: schedule
  schema: bronze
  description: Schedule of games

  columns:
    - name: game_date
      type: DATE
      nullable: false
      description: Date of the game

    - name: season
      type: INT
      nullable: false
      description: MLB season year

    - name: game_pk
      type: BIGINT
      nullable: false
      description: MLB unique identifier for the game

    - name: game_status
      type: STRING
      nullable: false
      description: Flag indicating the status of the game

    - name: ingestion_timestamp
      type: TIMESTAMP
      nullable: false
      description: Timestamp of when the data was ingested

  partition:
    field: season