table:
  name: test
  schema: bronze
  description: Test table

  columns:
    - name: game_id
      type: BIGINT
      nullable: false

    - name: game_date
      type: DATE
      nullable: false

    - name: team_id
      type: BIGINT
      nullable: true

  partition:
    field: game_date